# Generated by Django 4.0 on 2022-04-30 15:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
                ('language', models.CharField(choices=[('ENG', 'English'), ('ZH', 'Mandarin/Chinese'), ('HIN', 'Hindi'), ('SPA', 'Spanish'), ('FRA', 'French'), ('AR', 'Arabic'), ('BEN', 'Bengali'), ('RU', 'Russian'), ('POR', 'Portuguese'), ('IND', 'Indonesian'), ('DEU', 'German'), ('JPN', 'Japanese')], max_length=3)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound Sterling'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNH', 'Chinese Renminbi'), ('HKD', 'Hong Kong dollar'), ('NZD', 'New Zealand Dollar'), ('MXN', 'Mexican Peso'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham'), ('EGP', 'Egyptian Pound'), ('ARS', 'Argentine Peso'), ('BRL', 'Brazilian Real')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('information', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='api.provider')),
            ],
        ),
    ]
